export const metadata = {
  title: "Next App | Auth",
  description: "Generated by Next.js",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <h1>Auth Layout</h1>
      <div>{children}</div>
    </>
  );
}
